spring:
  application:
    name: springkey
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/SpringK
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  redis:
    host: localhost
  data:
    redis:
      port: 6379

jwt:
  auth:
    converter:
      resource-id: spring-client
      principal-attribute: preferred_username

logging:
  level:
    com.skey: DEBUG
  file:
    path: d:/workspace/prometheus_grafana/log

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
server:
  port: '8080'
info:
  app:
    website: 'springkey'
    version: 1
